name: Update Documentation Periodically

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours - reactivated July 2025

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install PyYAML
        run: pip install pyyaml requests

      - name: Update Documentation
        run: python ./scripts/update_docs.py

      - name: Commit and push changes
        id: auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatically update documentation from YAML"
          branch: main   

      - name: Trigger Pages rebuild
        if: steps.auto-commit.outputs.changes_detected == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'pages.yml',
              ref: 'main'
            })   
